let token=localStorage.getItem('gasnet_token'),ws,series={P:[],Q:[],U:[]};
const $=s=>document.querySelector(s), api=async(path,opt={})=>{opt.headers={...(opt.headers||{}),Authorization:`Bearer ${token}`};let r=await fetch(path,opt);if(!r.ok)throw Error((await r.json()).detail||'请求失败');return r.json()};
function showApp(){ $('#login').hidden=true;$('#app').hidden=false;loadModels(); }
if(token)showApp();
$('#loginForm').onsubmit=async e=>{e.preventDefault();let body=new URLSearchParams({username:$('#username').value,password:$('#password').value});try{let r=await fetch('/api/auth/token',{method:'POST',body});if(!r.ok)throw Error('用户名或密码错误');token=(await r.json()).access_token;localStorage.setItem('gasnet_token',token);showApp()}catch(x){$('#loginError').textContent=x.message}};
function logout(){localStorage.removeItem('gasnet_token');location.reload()} window.logout=logout;
setInterval(()=>$('#clock').textContent=new Date().toLocaleString(),1000);
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.page).classList.add('active');if(b.dataset.page==='alarms')loadAlarms();if(b.dataset.page==='history')loadHistory();if(b.dataset.page==='analysis')loadAnalysis()});
async function command(action){let s=await api('/api/simulation/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});setStatus(s.status);if(['start','resume'].includes(action))connect()}window.command=command;
function setStatus(s){$('#simStatus').textContent={running:'仿真运行中',paused:'仿真已暂停',stopped:'仿真已停止'}[s];$('#statusDot').style.background=s==='running'?'#35e6a1':'#667'}
function connect(){if(ws&&ws.readyState<2)return;ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws/monitor?token=${encodeURIComponent(token)}`);ws.onmessage=e=>render(JSON.parse(e.data));ws.onclose=()=>ws=null}
function render(d){setStatus(d.status);if(!d.P)return;$('#inlet').textContent=(Math.max(...d.P)+.3).toFixed(2);$('#totalFlow').textContent=d.Q.reduce((a,b)=>a+b,0).toFixed(1);$('#tick').textContent=d.tick;let level=d.overall_level||0,b=$('#riskBadge');b.className=`badge level${level}`;b.textContent=`Level ${level} ${['正常','注意','危险'][level]}`;
$('#liveRows').innerHTML=d.P.map((p,i)=>`<tr><td>支路 ${i+1}</td><td>${p.toFixed(3)}</td><td>${d.Q[i].toFixed(2)}</td><td>${d.U[i].toFixed(1)}</td><td class="level${d.risks?.[i]?.level||0}">${['正常','注意','危险'][d.risks?.[i]?.level||0]}</td></tr>`).join('');
$('#nodes').innerHTML=d.P.map((p,i)=>`<g><rect class="valve" x="${430}" y="${[50,160,270][i]}" width="70" height="38" rx="5"/><text x="465" y="${[74,184,294][i]}">V${i+1} ${d.U[i].toFixed(0)}%</text><circle class="load" cx="600" cy="${[70,180,290][i]}" r="42"/><text x="600" y="${[66,176,286][i]}">负荷${i+1}</text><text x="600" y="${[84,194,304][i]}">${p.toFixed(2)}MPa</text><path d="M500 ${[70,180,290][i]}H558"/></g>`).join('');
['P','Q','U'].forEach(k=>{series[k].push(d[k]);if(series[k].length>60)series[k].shift()});draw('pressureChart',series.P,['#19d3ff','#4cffac','#b375ff']);draw('flowChart',series.Q,['#ffae42','#19d3ff','#ff6680']);draw('valveChart',series.U,['#4cffac','#ffae42','#b375ff'])}
function draw(id,data,colors){let c=$('#'+id),r=c.getBoundingClientRect(),scale=devicePixelRatio||1;c.width=r.width*scale;c.height=r.height*scale;let x=c.getContext('2d');x.scale(scale,scale);x.strokeStyle='#173653';for(let i=1;i<5;i++){x.beginPath();x.moveTo(0,r.height*i/5);x.lineTo(r.width,r.height*i/5);x.stroke()}if(data.length<2)return;for(let j=0;j<3;j++){let vals=data.map(v=>v[j]),min=Math.min(...vals)*.9,max=Math.max(...vals)*1.1;if(max===min)max++;x.strokeStyle=colors[j];x.lineWidth=2;x.beginPath();vals.forEach((v,i)=>{let px=i*r.width/59,py=r.height-(v-min)/(max-min)*r.height*.85-r.height*.05;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()}}
async function loadModels(){try{let rows=await api('/api/models');$('#modelList').innerHTML=rows.map(x=>`<article><h2>${x.name}</h2><p>管径 ${x.diameter} m · 管长 ${x.length} km</p><p>入口 ${x.inlet_pressure} MPa · 额定流量 ${x.nominal_flow}</p><small>${x.valve_count} 个阀门</small></article>`).join('')}catch(e){logout()}}
$('#modelForm').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),n=3,v=Array.from({length:n},()=>({min_opening:0,max_opening:100,response_speed:20}));await api('/api/models',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:f.get('name'),diameter:+f.get('diameter'),length:+f.get('length'),inlet_pressure:+f.get('inlet_pressure'),nominal_flow:+f.get('nominal_flow'),valve_count:n,valves:v})});e.target.reset();loadModels()};
async function loadAlarms(){let x=await api('/api/alarms');$('#alarmTable').innerHTML=table(['时间','设备','类型','等级','状态','操作'],x.map(a=>[new Date(a.time).toLocaleString(),a.device,a.type,'Level '+a.level,a.status,a.status==='未处理'?`<button onclick="handleAlarm(${a.id})">确认处理</button>`:'-']))}async function handleAlarm(id){await api(`/api/alarms/${id}/handle`,{method:'PATCH'});loadAlarms()}window.handleAlarm=handleAlarm;
async function loadHistory(){let x=await api('/api/history?limit=100');$('#historyTable').innerHTML=table(['时间','支路','压力','流量','阀位','风险'],x.map(a=>[new Date(a.time).toLocaleString(),a.branch,a.pressure,a.flow,a.valve,'Level '+a.risk_level]))}
async function loadAnalysis(){let x=await api('/api/analysis/controllers');$('#analysisCards').innerHTML=x.map(a=>`<article><h2>${a.controller} 控制</h2><p>压力误差：<strong>${a.pressure_error}</strong></p><p>流量误差：<strong>${a.flow_error}</strong></p><p>阀门动作：<strong>${a.valve_actions}</strong> 次</p><p>稳定时间：<strong>${a.settling_time}</strong> s</p></article>`).join('')}
function table(h,rows){return `<table><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table>`}

